### PR TITLE
Add Deletion Log

### PR DESCRIPTION
**Pull request by raymondjxu**
Implements #1

Please let me know if there are specific things that you want here to address the concerns stated in the reply to the issue mentioned above.

### To-Do List
- [x] Implement API on server
- [x] Write unit tests for the API
- [x] Create edit log subpage on each profile
- [x] Make the edit log human readable
- [ ] Write unit tests for the new UI
- [x] Filter out deletions of cite-only "all rounds" disclosures (since those are usually just READMEs and would clutter up the logs)

### CODE REVIEW

**Comment by raymondjxu** [comment]
Screenshot 2024-10-30 at 15 31 59

**Comment by raymondjxu** [comment]
@ashtarcommunications ready for review, lmk if there's any issues. 

I didn't write a test for the UI yet as I have very little (read: zero) experience with vitest. For now, I think that it's probably better to put it in as a beta feature even if it doesn't have full code coverage.

**Comment by raymondjxu** [comment]
Bump?

**Comment by ashtarcommunications** [comment]
Thanks for your work on this. I have feedback/changes on the PR itself, but I'll hold off on that for now, as I think I need some more conceptual clarification about what this is trying to achieve.

Can you explain a little more about your rationale for wanting this feature in the first place, or what use case you envision? As I'm understanding the implementation here, this is just designed to display a list of previous round entries that have been deleted from the page, but without actually displaying any of the cite or open source content associated with it?

To be up front, based on my current understanding I am very reluctant to implement this. It feels like the motivation here is likely a desire on the part of competitors to know when one of their opponents has removed content from their page. That seems likely to just be an enabler for more bad theory arguments about disclosure norms. Philosophically, I do not think opponents are entitled to information that a team does not want to share (or decides to no longer share publicly). I think people *should* share openly, and opponents should be able to share intel amongst themselves, but I am not inclined to facilitate endless debates of the "you deleted your old 1AC from the caselist and we have proof" variety. My read on this is heavily influenced by experience; there used to be a more robust version history feature on the prior incarnation of the caselist, and I do not think it was a net positive for the community.

I also ran this basic feature idea by a number of folks in the HS community, and the reception was mostly negative. Several concerns were raised, mostly around people having what they felt were legitimate use cases for removing content from a page. I think much of that opposition is around having a cache of the actual deleted content (e.g. cites/docs), though I think some of the scenarios would also apply just to the minimal info shown in a deletion log. But the more minimal the log is (to address the content concerns), the less clear I am on the utility for it. Especially if it only covers deletions, and not other modifications.

Obviously the version history tables in the DB exist for a reason (disaster recovery, abuse prevention, etc), but I'm more inclined to think of those as an admin-only feature rather than a public facing data set.

As of now, based on the above and the negative feedback I received from others, I'm inclined not to merge this, but I'm willing to listen to the rationale for including it (or wait for additional feedback from others before making a final decision). It would need a number of changes before merging though (adding UI tests, removing some dev file inclusions, some minor nomenclature stuff, etc.).

**Comment by raymondjxu** [comment]
I'll be upfront: I'm aware we have very different ideas surrounding disclosure theory. I debate for a PF program that generally thinks disclosure is necessary to ensure good ethics and the only way to ensure it remains a norm (at least in this event) is through the win/loss from theory, and from your paradigm, I get the feeling that you don't really like disclosure theory debates. However, I don't think the implementation of an edit log will proliferate bad theory debates. Here are a couple thoughts I had.

1. Sometimes, I feel like I've disclosed something, and all of a sudden, it's no longer on my wiki page. I'm uncertain if this is caused by the disclosure failing to go through, or if somebody intentionally deleted something. Contacting support doesn't really solve back for this problem because usually nobody's sure and doesn't want to make a stink out of something that could be their own fault.
2. Other debaters I know (and trust) have claimed that their opponents deleted disclosures from their page to run disclosure theory on them. Having a deletion log with a name attached gets rid of those bad-faith disclosure debates when they _did_ disclose.
3. I'm inclined to believe that probably at least 80% of teams or 99% of competitive teams have deleted at least one round from their wiki because it initially had a mistake on it. I don't have any sources to back this up, but I'd assume you'd be able to check this. Given that, I'm inclined to believe that few people are going to run frivolous shells because otherwise the opponents get up and just say that they violate the shell anyways. Debaters are already using past screenshots to show that deletions have happened.
4. There's been an increasingly concerning trend of teams running theory positions (sometimes disclosure theory) at a tournament with more techy judges, then deleting all their disclosures immediately after the tournament, and then reposting them right before the first round of their next tournament. A deletion log would heavily discourage this practice. While I'd prefer not to single out teams here in a public space, I can definitely point to a couple examples if this is needed.

That being said, I think there's a case to be made that by limiting visibility of the edit log to the account linked to the page, we garner 90% of the benefits without risking any of the harms that mostly stem from opponents misusing access to the edit log of other teams. Or, we could show the edit log only to linked accounts until a certain number of deletions are reached.

I also don't think it would be a bad idea to experiment with doing this during one of the mid-season months: if it really becomes a drastic issue, it's very easily reversible.

**Comment by ashtarcommunications** [comment]
Thanks for the additional thoughts. I think the major point of departure on issues like this tends to be that students (understandably) think about these kind of design decisions through a competitive lens, and I tend to think more in terms of the pedagogical impacts and what kind of round content is being encouraged. I think it can simultaneously be true that disclosure is good, that it ought to be a norm, and that attempting to enforce that community-wide via in-round theory debates is a net negative. Broadly speaking, I am always going to be cautious about implementing features that seem like they could impact the way debates are litigated on a broad scale, and will always be reticent in places where a primary rationale for a proposal seems driven by competitive motivations.

That being said, I'm compelled by your second argument that having some level of transparency into page editing is a good deterrent against bad actors trying to game the system to induce theory debates on their terms. I think the general impression I get from the discussions I've had on this is that concerns over disclosure theory are largely non-unique. And if those debates are going to happen anyway, then having some level of accountability on who edited what and when might discourage more stupidity than it causes.

As such, I've gone ahead and implemented a version of this functionality separate from this PR. This was a great start and I definitely used your PR as inspiration - you deserve the credit both for initial code and pushing this issue to the forefront. My implementation differs in a few ways, in terms of where it lives in the UI (I don't want to mix "table filters" on the main rounds tables with non-rounds info), the exact data being returned (e.g. including edits as well as deletions, as well as a log on the school page, not just the team page), and some polishing stuff like front-end tests, matching existing code semantics, etc.

Rather than limit edit log access to a subset of users, I decided to just make the total amount of information returned relatively minimal. That is, the edit log shows that something was added/edited/deleted, but doesn't specify exactly what. I think that strikes a balance between providing enough info to discourage bad actors while not providing enough information to encourage nit-picking. And it avoids concerns over not being able to permanently remove problematic content. I think it's sufficient to deal with the majority of bad actor problems, e.g. it's easy to point and say "see, someone else deleted stuff on my page right before this round," or "see, I didn't make the changes you said I did."

The new UI is now live - I'll see what kind of feedback I get for the next couple of months and will decide on modifications or reversions then.

**Comment by ashtarcommunications** [comment]
Closed by #5db1739

**Pull request closed without merging**
